// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GqlTodo struct {
	ID   string   `json:"id"`
	Text string   `json:"text"`
	Done bool     `json:"done"`
	User *GqlUser `json:"user"`
}

type GqlUser struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
